
version: 2

models:
  - name: fct_wr_metrics
    description: "..."
    columns:
      - name: year
        description: "year of season"
        data_tests:
          - unique
          - not_null

  
